### PR TITLE
haiku: Add Haiku pkgman support

### PR DESCRIPTION
**Pull request by kallisti5**

### CODE REVIEW

**Comment by kallisti5** [comment]
```
/Data/Code/upt> uname -a
Haiku shredder 1 hrev54767 Dec  9 2020 07:46:05 x86_64 x86_64 Haiku
```

```
./target/debug/upt list -i | head -10
Status  Name                     Description                                                                             
-------------------------------------------------------------------------------------------------------------------------
s       a52dec                   An ATSC A/52 decoding library                                                           
s       artpaint                 A painting and image-processing program                                                 
s       aspell                   A free and open source spell checker                                                    
s       aspell_en                English dictionary for aspell program/library                                           
s       attica                   A library providing access to Open Collaboration services                               
s       autoconf                 A tool to automatically configure source code                                           
s       automake                 A tool for generating "Makefile.in" from "Makefile.am"                                  
s       bash                     The GNU Bourne Again Shell                   
```

```
./target/debug/upt install vim
100% repochecksum-1 [65 bytes]
Validating checksum for Haiku...done.
100% repochecksum-1 [64 bytes]
Validating checksum for HaikuPorts...done.
vim-8.2.1923-1 from repository system is already installed.
Nothing to do.
```

```
/Data/Code/upt> ./target/debug/upt remove vim
The following changes will be made:
  in system:
    uninstall package vim-8.2.1923-1
Continue? [yes/no] (yes) : 
```

**Comment by sigoden** [comment]
I don't know haiku very well. Give me some time to consider whether to merge.

**Comment by sigoden** [comment]
Upt only supports the OS built-in package management tool, so it is closed.

**Comment by kallisti5** [comment]
To clarify, hpkg / pkgman is the default package management tool on Haiku.

**Comment by sigoden** [comment]
I'm sorry I missed the Haiku.

Can you resubmit a PR? I am happy to support Haiku. @kallisti5

**Pull request closed without merging**
