### PR TITLE
haiku: Add Haiku pkgman support

### PR DESCRIPTION
**Pull request by kallisti5**

### CODE REVIEW

**Comment by sigoden** [comment]
I want to know if Rust supports Haiku? @kallisti5

**Comment by kallisti5** [comment]
I mean, this would be a silly thing to work on if it didn't :sweat_smile: 


Screenshot from 2023-12-13 08-17-15

**Comment by sigoden** [comment]
How to detect haiku? does `#[cfg(target_os = "haiku")]` work? @kallisti5

**Comment by kallisti5** [comment]
yup. that works.  Haiku is a tier 3 rust platform.

https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-3

**Comment by sigoden** [comment]
see #28

**Pull request closed without merging**
